require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SportsInterestsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # SportsInterest. As you add validations to SportsInterest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryGirl.build(:sports_interest).attributes
  }

  let(:invalid_attributes) {
    FactoryGirl.build(:sports_interest, user: nil).attributes
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SportsInterestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all sports_interests as @sports_interests" do
      sports_interest = SportsInterest.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:sports_interests)).to eq([sports_interest])
    end
  end

  describe "GET #show" do
    it "assigns the requested sports_interest as @sports_interest" do
      sports_interest = SportsInterest.create! valid_attributes
      get :show, params: {id: sports_interest.to_param}, session: valid_session
      expect(assigns(:sports_interest)).to eq(sports_interest)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new SportsInterest" do
        expect {
          post :create, params: {sports_interest: valid_attributes}, session: valid_session
        }.to change(SportsInterest, :count).by(1)
      end

      it "assigns a newly created sports_interest as @sports_interest" do
        post :create, params: {sports_interest: valid_attributes}, session: valid_session
        expect(assigns(:sports_interest)).to be_a(SportsInterest)
        expect(assigns(:sports_interest)).to be_persisted
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved sports_interest as @sports_interest" do
        post :create, params: {sports_interest: invalid_attributes}, session: valid_session
        expect(assigns(:sports_interest)).to be_a_new(SportsInterest)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested sports_interest" do
      sports_interest = SportsInterest.create! valid_attributes
      expect {
        delete :destroy, params: {id: sports_interest.to_param}, session: valid_session
      }.to change(SportsInterest, :count).by(-1)
    end
  end

end
